[package]
name = "csengeto_cli"
version = "1.0.2"
edition = "2024"

[dependencies]
chrono = { version = "0.4" }
lazy_static = "1.5.0"
reqwest = { version = "0.12.23", features = ["blocking"] }
rodio = "0.17"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
