[package]
name = "csengeto_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4" }
lazy_static = "1.5.0"
notify = { version = "8.0.0", features = ["serde"] }
rodio = "0.17"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
